### ISSUE TITLE
cannot convert 'char*' to 'char**' for argument '1' to 'void freeStr(char**)'

### ISSUE THREAD

**Issue by maujabur** [leftCoast/LC_lilParser#2]
Hi again!

I'm on arduino 1.8.19 with  LC_lilParser 1.2 and LC_baseTools 1.5.

When I try to compile the simple_parser_example I get the following:

`C:\Users\Fn\Documents\Arduino\libraries\LC_lilParser\src\lilParser.cpp: In destructor 'virtual cmdTemplate::~cmdTemplate()':
C:\Users\Fn\Documents\Arduino\libraries\LC_lilParser\src\lilParser.cpp:205:46: error: cannot convert 'char*' to 'char**' for argument '1' to 'void freeStr(char**)'
 cmdTemplate::~cmdTemplate(void) { freeStr(cmd); }
                                              ^
Usando a biblioteca LC_lilParser na versão 1.2 na pasta: C:\Users\Fn\Documents\Arduino\libraries\LC_lilParser 
Usando a biblioteca LC_baseTools-1.5 na versão 1.5 na pasta: C:\Users\Fn\Documents\Arduino\libraries\LC_baseTools-1.5 `

(I use the verbose option on preferences in order to get this kind of output(

**Comment by leftCoast** [comment]
Show me your line 206 in lilParser.cpp I saw this error before and I fixed it. I thought I released the fix and I bet I didn't. Lickly I just finished a project using all this stuff but I have the new un-released stuff here.

**Comment by leftCoast** [comment]
Are you on Arduino discord?

**Comment by leftCoast** [comment]
Ok try 1.3 I  (lilParser) +think+ it's fixed.

**Comment by maujabur** [comment]
Sorry, I fell asleep.

gonna try now, thanks!

I´ll let you know

**Comment by maujabur** [comment]
It works!

Thanks a lot!

**Comment by leftCoast** [comment]
Good! Sorry about the messed up versions and thanks for letting me know!
